a=10
print(type(a))
b=10.8
print(type(b))
c="vikash"
print(type(c))
d=[1,23,5,6]
print(type(d))
e=(1,2,3)
print(type(e))
f={'name':'vikash','batch_no':14}
print(type(f))
s={1,34,45}
print(type(s))
randomvar=True
print(type(randomvar))
random=None
print(type(random))
z=3j+2
print(type(z))
frozenset(["name","age"])
print(frozenset)
print(type(frozenset))